name: Build
on:
  push:
    branches:
      - master
      - 'renovate/**'
      - 'github-renovate/**'
    paths:
      - '.github/workflows/build.yml'
      - '.dockerignore'
      - 'docker/*.Dockerfile'
      - 'src/**'
  pull_request:
    branches-ignore:
      - 'renovate/**'
      - 'github-renovate/**'
    paths:
      - '.github/workflows/build.yml'
      - '.dockerignore'
      - 'docker/*.Dockerfile'
      - 'src/**'
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        version: [ubuntu-14.04, ubuntu-16.04, ubuntu-18.04, ubuntu-20.04]
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: Docker build and push
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: vidavidorra/${{ matrix.version }}
          dockerfile: docker/${{ matrix.version }}.Dockerfile
          tag_with_ref: ${{ github.event_name == 'pull_request' }}
          tag_with_sha: true
